### ISSUE TITLE
Formerly working code failed in 5.0.0

### ISSUE THREAD

**Issue by exoego** [mikolajmitura/java-properties-to-json#51]
I ran the below code using `java-properties-to-json` version `3.2` for a year.

```java
var properties = new Properties();
properties.load(new InputStreamReader(new FileInputStream(sourceFile), "UTF-8"));
var typeResolvers = new StringJsonTypeResolver();
var jsonContent = new PropertiesToJsonConverter(typeResolvers).parseToJson(properties);
```

against properties file like below

```properties
foo.bar1=foo
foo.bar2=buz
```

While updating to `5.0.0`, I found a trivial compile error since `parseToJson` is deleted, so I changed it to `convertToJson`.
Then it compiles fine, but now produces the following `NoSuchMethodError` on runtime (actually I coded in Scala language).

I am not sure this is bug in this library, or my code.
It would be helpful if I got some guidance to migrate this code.

```
[error] java.lang.NoSuchMethodError: 'void com.google.gson.Gson.<init>(com.google.gson.internal.Excluder, com.google.gson.FieldNamingStrategy, java.util.Map, boolean, boolean, boolean, boolean, boolean, boolean, boolean, com.google.gson.LongSerializationPolicy, java.lang.String, int, int, java.util.List, java.util.List, java.util.List)'
[error]         at com.google.gson.GsonBuilder.create(GsonBuilder.java:597)
[error]         at pl.jalokim.propertiestojson.util.PropertiesToJsonConverter.prettifyOfJson(PropertiesToJsonConverter.java:397)
[error]         at pl.jalokim.propertiestojson.util.PropertiesToJsonConverter.convertFromValuesAsObjectMap(PropertiesToJsonConverter.java:390)
[error]         at pl.jalokim.propertiestojson.util.PropertiesToJsonConverter.convertToJson(PropertiesToJsonConverter.java:286)
[error]         at $caa0b639eec2060fea9e$.$anonfun$genLocale$4(build.sbt:170)
[error]         at $caa0b639eec2060fea9e$.$anonfun$genLocale$4$adapted(build.sbt:162)
[error]         at scala.collection.IndexedSeqOptimized.foreach(IndexedSeqOptimized.scala:32)
[error]         at scala.collection.IndexedSeqOptimized.foreach$(IndexedSeqOptimized.scala:29)
[error]         at scala.collection.mutable.ArrayOps$ofRef.foreach(ArrayOps.scala:194)
[error]         at $caa0b639eec2060fea9e$.$anonfun$genLocale$1(build.sbt:162)
[error]         at $caa0b639eec2060fea9e$.$anonfun$genLocale$1$adapted(build.sbt:131)
[error]         at scala.Function1.$anonfun$compose$1(Function1.scala:44)
[error]         at sbt.internal.util.$tilde$greater.$anonfun$$u2219$1(TypeFunctions.scala:40)
[error]         at sbt.std.Transform$$anon$4.work(System.scala:67)
[error]         at sbt.Execute.$anonfun$submit$2(Execute.scala:269)
[error]         at sbt.internal.util.ErrorHandling$.wideConvert(ErrorHandling.scala:16)
[error]         at sbt.Execute.work(Execute.scala:278)
[error]         at sbt.Execute.$anonfun$submit$1(Execute.scala:269)
[error]         at sbt.ConcurrentRestrictions$$anon$4.$anonfun$submitValid$1(ConcurrentRestrictions.scala:178)
[error]         at sbt.CompletionService$$anon$2.call(CompletionService.scala:37)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
[error]         at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[error]         at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[error]         at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by mikolajmitura** [comment]
hm, it looks like that you have another version of com.google.code.gson:gson in your libraries... 
If you use maven to build then can do like below:

You can use maven dependency tree to see from where your current version of gson comes... 
the entry with your current version of gson will not have "omitted for conflict with"

https://maven.apache.org/plugins/maven-dependency-plugin/examples/resolving-conflicts-using-the-dependency-tree.html 

then you can exclude this like below:
```xml
<dependency>
      <groupId>sample.ProjectA</groupId> <!--groupId from where comes another version of gson -->
      <artifactId>Project-A</artifactId>
      <version>1.0</version>
      <exclusions>
        <exclusion>  <!-- declare the exclusion here -->
          <groupId>com.google.code.gson</groupId>
          <artifactId>gson</artifactId>
        </exclusion>
      </exclusions> 
    </dependency>
```
example how to exclude...
https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

**Comment by exoego** [comment]
Thanks for detail !!

It is true that there is a conflict between dependencies that uses gson.

```
[info]  * com.google.code.gson:gson:2.8.5 is selected over 2.7
[info]      +- pl.jalokim.propertiestojson:java-properties-to-json:5.0.0 (depends on 2.8.5)
[info]      +- com.google.javascript:closure-compiler:v20190513   (depends on 2.7)
```

I will close this since this is my project issue and workaround.
